#!/bin/sh

HOUSEAPP=housesaga

case $1 in
    configure|abort-upgrade|abort-deconfigure|abort-remove)
        . /usr/local/share/house/postinstall
        chown -R house:house /var/lib/house/log
        ;;
esac

